In [5]:
import numpy as np

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


ASSIGNMENT

In [18]:
# 1.	Generate a tuple from the set
sets = ["aman", "222", 777, 400.4]
t = tuple(sets)
print(t)
# 2.Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth.
#Print out the values and keys.
d = {'First Name':'Sanjana','RollNo':'CB.SC.U4CSE23751','Last Name':'V','dob':'21-02-2005'}
print(d.keys())
print(d.values())
# 3.	Use rand function to generate a 2-dimensional random array with seed.
'''from numpy import random
arr = random.randint(100,size=(2,3))
print(arr)'''
from numpy import random
np.random.seed(0)
arr = np.random.rand(2,3)
print(arr)
# 4.Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)
x = random.rand()
print(x)
print(abs(-1234))
# 5.	Return a random integer N such that 20 <= N <= 90.
x = random.randint(20,90)
print(x)

('aman', '222', 777, 400.4)
dict_keys(['First Name', 'RollNo', 'Last Name', 'dob'])
dict_values(['Sanjana', 'CB.SC.U4CSE23751', 'V', '21-02-2005'])
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]
0.4375872112626925
1234
32


In [37]:
import random
# 6.	Given a population or set[11, 12, 13,14, 15]
# o	Return a 3 length list of unique elements without replacement.
population = [11,12, 13,14,15]
arr = random.sample(population,3)
print(arr)
# o	Shuffle the above set
arr2  = population.copy()
random.shuffle(arr2)
print(arr2)
# o	Print a random number from the set
x = random.choice(population)
print(x)
'''7.	Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.
8.	Create an illustrative function to demonstrate use of: (a) if, elif and else (b) for, while, break and continue.
9.	Given a string "The King is Dead, Long Live The King"
o	Print the complete string
o	Print first character of the string
o	Print characters starting from 3rd to 5th
o	Print string starting from 3rd character
o	Split the words'''
# 10.	An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).
# Slice the above array to display first and second elements
arr = np.array([1,4,5,8],dtype='f')
print(arr)
print(arr[1:3])

[12, 13, 14]
[15, 13, 14, 12, 11]
15
[1. 4. 5. 8.]
[4. 5.]


In [52]:
# 11.	Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).
arr = np.array([[1,2,3],[4,5,6]])
# 12.	Array slicing works with multiple dimensions in the same way as usual, applying each slice specification
# as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).
# o	Slice and display the 2nd row.
row2 = arr[1]
print(row2)
# o	Write code to display as array([2., 5.])
arr1 = np.array(arr[:,1])
print(arr1)
# o	Find the length of the array.
print(len(arr))
# 13.	Arrays can be reshaped using tuples that specify new dimensions.
#Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has
#five elements and whose second axis has two elements. Obtain the transpose of the array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
new_arr = arr.reshape(5,2)
print(new_arr.T)
# 14.	Create an array from a list of 1,2 and 3.
arr1 = np.array([1,2,3])
# 15.	Fill an array [1,2,3] with a single value [9,9,9].
new = np.full_like(arr1,9)
print(new)

[4 5 6]
[2 5]
2
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


array([9, 9, 9])

In [61]:
# 1.	Sum the elements of array [2,4,5].
print(np.sum([2,4,5]))
# 2.	Give the products of array [77,74,75]
print(np.prod([77,74,75]))
# 3.	Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.
print(np.mean([2,1,9,1,2,22,1,1,4,55,6,2,56]))
print(np.median([2,1,9,1,2,22,1,1,4,55,6,2,56]))
print(np.std([2,1,9,1,2,22,1,1,4,55,6,2,56]))
print(np.argmin([2,1,9,1,2,22,1,1,4,55,6,2,56]))
print(np.min([2,1,9,1,2,22,1,1,4,55,6,2,56]))
print(np.max([2,1,9,1,2,22,1,1,4,55,6,2,56]))
print(np.var([2,1,9,1,2,22,1,1,4,55,6,2,56]))
print()
# 4.	Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.
print(np.unique([1, 1, 4, 5, 5, 5, 7] ))
# 5.	Find dot product of two arrays [1, 2, 3]and [0, 1, 1].
a = [1,2,3]
b = [0,1,1]
print(np.dot(a,b))
# 6.	Find the eigenvalues and eigenvectors of matrix A.
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
# 7.	Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats.
# Find the correlation coefficients.
data = np.array([[11, 22, 11, 31], [25, 33, 31, 28]], dtype=float)
correlation_matrix = np.corrcoef(data)
print("Correlation Coefficients:\n", correlation_matrix)


11
427350
12.461538461538462
2.0
19.165736192147232
1
1
56
367.32544378698225

[1 4 5 7]
5
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Correlation Coefficients:
 [[1.         0.15997968]
 [0.15997968 1.        ]]
