In [1]:
import numpy as np
import pandas as pd

In [4]:
data = [[1,1],[2,3],[3,2],[4,5],[5,4]]
A = pd.DataFrame(data,columns=['Feature 1','Feature 2'])
A

Feature 1  Feature 2
0          1          1
1          2          3
2          3          2
3          4          5
4          5          4

In [6]:
#centre the dataset
M=np.mean(A.T,axis=1)
M
#A.mean(axis=0)

Feature 1    3.0
Feature 2    3.0
dtype: float64

In [9]:
#find centered dataset
C = A -M
C

Feature 1  Feature 2
0       -2.0       -2.0
1       -1.0        0.0
2        0.0       -1.0
3        1.0        2.0
4        2.0        1.0

In [10]:
#calculate covarience matrix

cov = np.dot(C.T,C)/(C.shape[0]-1)
cov

array([[2.5, 2. ],
       [2. , 2.5]])

In [11]:
#find eigen values and vectors 
e_val = (np.linalg.eig(cov))[0]
e_val

array([4.5, 0.5])

In [12]:
e_vec = (np.linalg.eig(cov))[1]
e_vec

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [14]:
#principal axis value to higher value of 4.4
V = e_vec[:,1]
V

array([-0.70710678,  0.70710678])

In [15]:
#final matrix
final_mat = np.dot(C,V)
print(final_mat)

[-4.44089210e-16  7.07106781e-01 -7.07106781e-01  7.07106781e-01
 -7.07106781e-01]
